"""sync_models_with_schema

Revision ID: fe7db3bf61ca
Revises: 0ec82046918a
Create Date: 2026-06-30 20:03:23.682654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe7db3bf61ca'
down_revision: Union[str, None] = '0ec82046918a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Pre-create the Postgres ENUM types: the ALTER ... USING casts below
    # reference them, and that cast bypasses SQLAlchemy's automatic enum
    # creation. checkfirst makes it idempotent; it's a no-op on SQLite (which
    # renders Enum as VARCHAR), keeping the migration portable.
    bind = op.get_bind()
    sa.Enum('MARKETING', 'TRANSACTIONAL', 'NEWSLETTER', 'PROMOTIONAL', 'ANNOUNCEMENT', 'OTHER', name='campaigntype').create(bind, checkfirst=True)
    sa.Enum('DRAFT', 'SCHEDULED', 'SENDING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='campaignstatus').create(bind, checkfirst=True)

    with op.batch_alter_table('campaign_smtp_configs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        # postgresql_using: VARCHAR values are the enum label strings already,
        # so cast via text. (No-op on SQLite, which renders Enum as VARCHAR.)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('MARKETING', 'TRANSACTIONAL', 'NEWSLETTER', 'PROMOTIONAL', 'ANNOUNCEMENT', 'OTHER', name='campaigntype', create_type=False),
               nullable=False,
               postgresql_using='type::text::campaigntype')
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('DRAFT', 'SCHEDULED', 'SENDING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='campaignstatus', create_type=False),
               existing_nullable=False,
               postgresql_using='status::text::campaignstatus')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('from_name')
        batch_op.drop_column('from_email')

    with op.batch_alter_table('emaillogs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('error_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_index('ix_emaillogs_recipient_last_event')
        batch_op.drop_index('ix_emaillogs_correlation_id')
        batch_op.create_index(batch_op.f('ix_emaillogs_correlation_id'), ['correlation_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_emaillogs_campaign_id'), ['campaign_id'], unique=False)
        batch_op.drop_constraint('emaillogs_campaign_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('emaillogs_recipient_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'smtpservers', ['smtp_server_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('attempt_count')
        batch_op.drop_column('smtp_server')
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('is_transient')
        batch_op.drop_column('bounced_at')

    with op.batch_alter_table('recipientlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invalid_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('duplicate_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('suppressed_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('settings', sa.JSON(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_recipientlists_name'), ['name'], unique=False)

    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_part', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('domain', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('domain_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_suppressed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('company', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('validation_error', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('recipient_list_id', sa.Integer(), nullable=True))
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint('recipients_list_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipientlists', ['recipient_list_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('list_id')

    with op.batch_alter_table('smtpservers', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_variants', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('placeholders_used', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('attachment_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('attachment_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('settings', sa.JSON(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('variables')
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('variables', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('settings')
        batch_op.drop_column('tags')
        batch_op.drop_column('attachment_type')
        batch_op.drop_column('attachment_path')
        batch_op.drop_column('placeholders_used')
        batch_op.drop_column('is_default')
        batch_op.drop_column('subject_variants')

    with op.batch_alter_table('smtpservers', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recipients_list_id_fkey', 'recipientlists', ['list_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('recipient_list_id')
        batch_op.drop_column('validation_error')
        batch_op.drop_column('company')
        batch_op.drop_column('is_suppressed')
        batch_op.drop_column('domain_name')
        batch_op.drop_column('domain')
        batch_op.drop_column('local_part')

    with op.batch_alter_table('recipientlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipientlists_name'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('settings')
        batch_op.drop_column('tags')
        batch_op.drop_column('suppressed_count')
        batch_op.drop_column('duplicate_count')
        batch_op.drop_column('invalid_count')

    with op.batch_alter_table('emaillogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bounced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_transient', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('smtp_server', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('attempt_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('emaillogs_recipient_id_fkey', 'recipients', ['recipient_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('emaillogs_campaign_id_fkey', 'campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_emaillogs_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_emaillogs_correlation_id'))
        batch_op.create_index('ix_emaillogs_correlation_id', ['correlation_id'], unique=False)
        batch_op.create_index('ix_emaillogs_recipient_last_event', ['recipient_email', 'last_event_at'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('error_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('from_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Enum('DRAFT', 'SCHEDULED', 'SENDING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='campaignstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.Enum('MARKETING', 'TRANSACTIONAL', 'NEWSLETTER', 'PROMOTIONAL', 'ANNOUNCEMENT', 'OTHER', name='campaigntype'),
               type_=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('campaign_smtp_configs', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###

