"""Add identity and settings models

Revision ID: f76827f0acc7
Revises: 6a8d103842df
Create Date: 2026-01-06 12:40:34.795550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f76827f0acc7'
down_revision: Union[str, None] = '6a8d103842df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('from_emails',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_from_emails_email'), 'from_emails', ['email'], unique=True)
    op.create_table('global_settings',
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('hourly_limit', sa.Integer(), nullable=False),
    sa.Column('min_delay', sa.Float(), nullable=False),
    sa.Column('max_delay', sa.Float(), nullable=False),
    sa.Column('default_reply_to', sa.String(length=255), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('retry_delay_base', sa.Integer(), nullable=True),
    sa.Column('smtp_timeout', sa.Integer(), nullable=True),
    sa.Column('dns_timeout', sa.Integer(), nullable=True),
    sa.Column('max_concurrency', sa.Integer(), nullable=True),
    sa.Column('proxy_enabled', sa.Boolean(), nullable=True),
    sa.Column('proxy_list', sa.JSON(), nullable=True),
    sa.Column('proxy_rotation_strategy', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sender_names',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sender_names_name'), 'sender_names', ['name'], unique=False)
    op.drop_index('ix_dead_letters_campaign_id', table_name='dead_letters')
    op.drop_index('ix_dead_letters_correlation_id', table_name='dead_letters')
    op.drop_index('ix_dead_letters_recipient', table_name='dead_letters')
    op.drop_table('dead_letters')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dead_letters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('recipient', sa.VARCHAR(length=255), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=500), nullable=False),
    sa.Column('html_body', sa.TEXT(), nullable=False),
    sa.Column('from_email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('from_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('campaign_id', sa.INTEGER(), nullable=True),
    sa.Column('correlation_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('error_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=False),
    sa.Column('smtp_server', sa.VARCHAR(length=100), nullable=True),
    sa.Column('smtp_response', sa.TEXT(), nullable=True),
    sa.Column('failed_at', sa.DATETIME(), nullable=False),
    sa.Column('retry_count', sa.INTEGER(), nullable=False),
    sa.Column('last_retry_at', sa.DATETIME(), nullable=True),
    sa.Column('resolved', sa.BOOLEAN(), nullable=False),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.Column('resolution_notes', sa.TEXT(), nullable=True),
    sa.Column('additional_data', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dead_letters_recipient', 'dead_letters', ['recipient'], unique=False)
    op.create_index('ix_dead_letters_correlation_id', 'dead_letters', ['correlation_id'], unique=False)
    op.create_index('ix_dead_letters_campaign_id', 'dead_letters', ['campaign_id'], unique=False)
    op.drop_index(op.f('ix_sender_names_name'), table_name='sender_names')
    op.drop_table('sender_names')
    op.drop_table('global_settings')
    op.drop_index(op.f('ix_from_emails_email'), table_name='from_emails')
    op.drop_table('from_emails')
    # ### end Alembic commands ###

