"""Restore DeadLetter

Revision ID: a9fac8c2c465
Revises: f76827f0acc7
Create Date: 2026-01-06 12:41:38.311293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9fac8c2c465'
down_revision: Union[str, None] = 'f76827f0acc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dead_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('html_body', sa.Text(), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('smtp_server', sa.String(length=100), nullable=True),
    sa.Column('smtp_response', sa.Text(), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letters_campaign_id'), 'dead_letters', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_dead_letters_correlation_id'), 'dead_letters', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_dead_letters_recipient'), 'dead_letters', ['recipient'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dead_letters_recipient'), table_name='dead_letters')
    op.drop_index(op.f('ix_dead_letters_correlation_id'), table_name='dead_letters')
    op.drop_index(op.f('ix_dead_letters_campaign_id'), table_name='dead_letters')
    op.drop_table('dead_letters')
    # ### end Alembic commands ###

